<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <RootNamespace>MapLibrary</RootNamespace>
    <AssemblyName>MapLibrary</AssemblyName>
    <OutputType>Library</OutputType>
    <PlatformTarget>x64</PlatformTarget>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DynamicData" Version="6.15.1" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="4.7.0" />
    <PackageReference Include="Pharmacist.Common" Version="1.5.15" />
    <PackageReference Include="ReactiveUI" Version="11.4.17" />
    <PackageReference Include="ReactiveUI.Events.Winforms" Version="11.4.17" />
    <PackageReference Include="ReactiveUI.Fody" Version="11.4.17" />
    <PackageReference Include="ReactiveUI.Validation" Version="1.4.15" />
    <PackageReference Include="ReactiveUI.WinForms" Version="11.4.17" />
    <PackageReference Include="Serilog" Version="2.9.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Splat" Version="9.5.6" />
    <PackageReference Include="System.Reactive" Version="4.4.1" />
    <PackageReference Include="System.Resources.Extensions" Version="5.0.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.3" />
    <PackageReference Include="System.Security.AccessControl" Version="4.7.0" />
    <PackageReference Include="System.Security.Principal.Windows" Version="4.7.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="gdal_csharp">
      <HintPath>..\..\Apis\bin\gdal\csharp\gdal_csharp.dll</HintPath>
    </Reference>
    <Reference Include="mapscript_csharp">
      <HintPath>..\..\Apis\bin\ms\csharp\mapscript_csharp.dll</HintPath>
    </Reference>
    <Reference Include="ogr_csharp">
      <HintPath>..\..\Apis\bin\gdal\csharp\ogr_csharp.dll</HintPath>
    </Reference>
    <Reference Include="osr_csharp">
      <HintPath>..\..\Apis\bin\gdal\csharp\osr_csharp.dll</HintPath>
    </Reference>
    <Reference Include="ScintillaNet">
      <HintPath>..\ExternalFiles\ScintillaNet.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MapManager.Apis\MapManager.Apis.csproj" />
    <ProjectReference Include="..\MapManager.ViewModels\MapManager.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
    <None Include="app.config" />
    <None Include="Images\**\*" />
    <None Include="Cursors\**\*" />
    <None Include="packages.config" />
    <None Include="Resources\MapManager.ico" />
  </ItemGroup>

  <Import Project="..\packages\Fody.6.2.0\build\Fody.targets" Condition="Exists('..\packages\Fody.6.2.0\build\Fody.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Fody.6.2.0\build\Fody.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Fody.6.2.0\build\Fody.targets'))" />
    <Error Condition="!Exists('..\packages\ReactiveUI.Fody.11.4.17\build\ReactiveUI.Fody.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\ReactiveUI.Fody.11.4.17\build\ReactiveUI.Fody.props'))" />
  </Target>

</Project>